language: php

matrix:
  allow_failures:
    - php: 7.0

php:
  - 5.5
  - 5.6
  - 7.0

branches:
  only:
    - master
    - develop

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - composer self-update
  - composer install --dev
  - mkdir -p build/logs

script:
  vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
